# Assignments: Prepping for Modeling

## 1. Create a Single Table

Hi there,

We just finished collecting our Q2 book sales data. Can you help us create one giant table that includes:

* April, May and June’s book sales
* Customer data

Each table has a field called customer_id that links all the tables together.

I’ve attached four files.

Thanks!\
Brooke

In [1]:
# Read all four files into a Jupyter Notebook
import pandas as pd

df_april = pd.read_excel('../Data/Book_Sales_April.xlsx')
df_may = pd.read_excel('../Data/Book_Sales_May.xlsx')
df_june = pd.read_excel('../Data/Book_Sales_June.xlsx')
df_customers = pd.read_csv('../Data/Book_Customers.csv')

In [2]:
df_april.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02

In [3]:
df_may.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date
0,414,109,The Concert Hall,Adults,Fiction,22.72,4.7,Online,2023-05-01
1,415,110,Space and Time,Adults,Fiction,21.58,3.7,In Person,2023-05-04
2,416,101,Rainbows,Children,Fiction,10.25,4.7,Online,2023-05-04
3,417,104,The Speed of Light,Adults,Fiction,20.32,4.1,In Person,2023-05-04
4,418,106,Real Dinosaurs,Children,Non-Fiction,9.99,3.4,In Person,2023-05-04

In [4]:
df_june.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date
0,432,117,Blue Waters,Adults,Fiction,23.98,2.6,Online,2023-06-05
1,433,118,The Cave,Adults,Fiction,24.99,4.7,Online,2023-06-07
2,434,106,Best Dinosaur Book Ever,Children,Non-Fiction,10.49,4.7,In Person,2023-06-08
3,435,103,Peter Penn: The Untold Story,Adults,Non-Fiction,27.90,4.8,In Person,2023-06-08
4,436,101,Everything is Amazing,Children,Fiction,4.99,3.9,In Person,2023-06-08

In [5]:
df_customers.head()

   Customer ID Customer Name  Age Has School Aged Children Has_Pets
0          101     Alexander   36                      Yes       No
1          102         Mason   16                       No       No
2          103         Ethan   55                       No       No
3          104        Daniel   70                       No       No
4          105       Michael   18                       No      Yes

In [6]:
# Concatenate the April, May and June book sales DataFrames
df_sales = pd.concat([df_april, df_may, df_june]).reset_index(drop=True)
df_sales.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02

In [7]:
# Join the newly created book sales DataFrame with the customers DataFrame on customer_id
# Which type of join do you think would work best here?
df = df_sales.merge(df_customers, how="left", on="Customer ID")
df.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date,Customer Name,Age,Has School Aged Children,Has_Pets
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01,Alexander,36,Yes,No
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01,Alexander,36,Yes,No
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02,Mason,16,No,No
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02,Mason,16,No,No
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02,Mason,16,No,No

## 2. Prepare Rows for Modeling

Hi again,

We are trying to predict which customers will purchase a book this month.

Can you reformat the data you compiled earlier this week so that it’s ready to be input into a model, with each row representing a customer instead of a purchase?

Thanks!\
Brooke

In [8]:
# What should one row of data look like for the model?
df_prev = df[df['Purchase Date'].dt.month < 6]
df_now = df[df['Purchase Date'].dt.month == 6]

In [9]:
# Create a column called 'June Purchases' that sums up all purchases in June
df_purchase = df_now.groupby('Customer ID').size().reset_index(name='June Purchases')
df_purchase

    Customer ID  June Purchases
0           101               2
1           103               1
2           106               1
3           108               1
4           111               2
5           117               1
6           118               1
7           119               1
8           120               2
9           121               1
10          122               3
11          123               1
12          124               1
13          125               1

In [10]:
# Create a column called 'Total Spend' that sums up the prices of all the books that were purchased in April and May
df_total_spend = df_prev.groupby('Customer ID').Price.sum().reset_index(name='Total Spend')
df_total_spend

    Customer ID  Total Spend
0           101        33.71
1           102        79.96
2           103        55.20
3           104        42.32
4           105        21.50
5           106        38.96
6           107        25.99
7           108         9.20
8           109        22.72
9           110        21.58
10          111        40.50
11          112        35.50
12          113        28.99
13          114        28.50
14          115        27.60
15          116        24.99

In [11]:
# Combine the 'June Purchases' and 'Total Spend' columns into a single DataFrame for modeling
df_combine = df_total_spend.merge(df_purchase, how='left', on='Customer ID').fillna(0)
df_combine

    Customer ID  Total Spend  June Purchases
0           101        33.71             2.0
1           102        79.96             0.0
2           103        55.20             1.0
3           104        42.32             0.0
4           105        21.50             0.0
5           106        38.96             1.0
6           107        25.99             0.0
7           108         9.20             1.0
8           109        22.72             0.0
9           110        21.58             0.0
10          111        40.50             2.0
11          112        35.50             0.0
12          113        28.99             0.0
13          114        28.50             0.0
14          115        27.60             0.0
15          116        24.99             0.0

## 3. Prepare Columns for Modeling

Hi again,

Thanks for your help earlier this week! We just learned that we also have to make all of the data numeric before inputting it into a predictive model.

Can you turn the Audience text field into a numeric field?

Thanks!\
Brooke

In [12]:
# Change the Audience field into a dummy variable
# INPUT에 대해서만 더미를 만든다
df_audience_dummies = pd.get_dummies(df_prev.Audience, dtype=int)
df_audience_dummies

    Adults  Children  Teens
0        0         1      0
1        0         1      0
2        0         0      1
3        0         0      1
4        0         0      1
5        1         0      0
6        1         0      0
7        1         0      0
8        0         1      0
9        0         0      1
10       0         1      0
11       1         0      0
12       0         1      0
13       1         0      0
14       1         0      0
15       0         1      0
16       1         0      0
17       0         1      0
18       0         1      0
19       0         0      1
20       0         0      1
21       0         0      1
22       1         0      0
23       1         0      0
24       1         0      0
25       1         0      0
26       0         1      0
27       0         1      0
28       0         0      1
29       0         0      1
30       1         0      0

In [13]:
# Using the Audience dummy variables, create three new columns that contain
# the number of Adult / Children / Teen books purchased by each customer
df_contain = pd.concat([df_prev['Customer ID'], df_audience_dummies], axis=1)
df_contain = df_contain.groupby('Customer ID').sum().reset_index()
df_contain

    Customer ID  Adults  Children  Teens
0           101       0         5      0
1           102       0         0      4
2           103       2         0      0
3           104       2         0      0
4           105       1         0      0
5           106       0         4      0
6           107       1         0      0
7           108       0         1      0
8           109       1         0      0
9           110       1         0      0
10          111       0         0      3
11          112       0         0      2
12          113       1         0      0
13          114       1         0      0
14          115       1         0      0
15          116       1         0      0

In [14]:
# Combine the three new columns back with the customer-level data
df_combine = df_combine.merge(df_contain, how='left', on='Customer ID')
df_combine

    Customer ID  Total Spend  June Purchases  Adults  Children  Teens
0           101        33.71             2.0       0         5      0
1           102        79.96             0.0       0         0      4
2           103        55.20             1.0       2         0      0
3           104        42.32             0.0       2         0      0
4           105        21.50             0.0       1         0      0
5           106        38.96             1.0       0         4      0
6           107        25.99             0.0       1         0      0
7           108         9.20             1.0       0         1      0
8           109        22.72             0.0       1         0      0
9           110        21.58             0.0       1         0      0
10          111        40.50             2.0       0         0      3
11          112        35.50             0.0       0         0      2
12          113        28.99             0.0       1         0      0
13          114        28.50             0.0       1         0      0
14          115        27.60             0.0       1         0      0
15          116        24.99             0.0       1         0      0

## 4. Feature Engineering

Hi again,

I have one final request for you.

As a reminder, our goal is to try and predict which customer will purchase a book this month.

Can you create new features that you think will do a good job making a prediction?

Thanks!\
Brooke

In [22]:
df.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date,Customer Name,Age,Has School Aged Children,Has_Pets
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01,Alexander,36,Yes,No
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01,Alexander,36,Yes,No
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02,Mason,16,No,No
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02,Mason,16,No,No
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02,Mason,16,No,No

In [ ]:
# what features could do a good job predicting june purchases?

In [16]:
# create the feature

In [17]:
# add it to the dataframe for modeling

In [18]:
# create another feature

In [19]:
# add it to the dataframe for modeling

In [20]:
# view the final dataframe that is ready to be input into a model