# Assignments: Cleaning Data

## 1. Data in Python Request

* Read in data from the Excel spreadsheet (Alarm Survey Data.xlsx) and put into a Pandas DataFrame
* Check the data type of each column
* Convert object columns into numeric or datetime columns, as needed

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_excel('../Data/Alarm Survey Data.xlsx')
df.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3.0,active,3.0,1,5 stars
1,2,31,3.0,light,3.0,3,3 stars
2,3,18,0.0,light_activity,4.0,1,1 stars
3,4,42,4.0,active,4.0,1,4 stars
4,5,30,1.0,light_activity,1.0,4,3 stars

In [2]:
df.describe()

,survey_id,age,number_of_children,sleep_quality,number_of_snoozes
count,6433.000000,6433.000000,6433.000000,6082.000000,6433.000000
mean,3216.302192,29.069175,1.395616,4.232654,1.145811
std,1856.007409,7.472048,1.432192,0.842448,1.599481
min,1.000000,13.000000,0.000000,1.000000,0.000000
25%,1609.000000,23.000000,0.000000,4.000000,0.000000
50%,3217.000000,28.000000,1.000000,4.000000,0.000000
75%,4825.000000,34.000000,2.000000,5.000000,2.000000
max,6366.000000,47.000000,5.500000,5.000000,19.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 351.9+ KB

In [4]:
df.activity_level.value_counts()

activity_level
active            2450
lightly active    2289
light_activity     691
very active        669
light              334
Name: count, dtype: int64

In [5]:
df.alarm_rating.value_counts()

alarm_rating
3 stars    2155
2 stars    2103
4 stars     996
5 stars     794
1 stars     385
Name: count, dtype: int64

In [6]:
df.alarm_rating = df.alarm_rating.str.replace(' stars', '').astype(int)
df.alarm_rating.value_counts()

alarm_rating
3    2155
2    2103
4     996
5     794
1     385
Name: count, dtype: int64

## 2. Missing Data Check

* Find any missing data
* Deal with the missing data

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   int64
dtypes: float64(2), int64(4), object(1)
memory usage: 351.9+ KB

In [15]:
df[df.isna().any(axis=1)]

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
10,11,28,2.0,lightly active,NaN,3,4
18,19,38,2.0,lightly active,NaN,1,5
23,24,24,2.0,very active,NaN,1,5
26,27,25,2.0,lightly active,NaN,1,2
28,29,29,2.0,lightly active,NaN,1,2
...,...,...,...,...,...,...,...
6310,6311,30,2.0,very active,NaN,0,3
6319,6320,44,2.0,lightly active,NaN,0,3
6375,6309,32,3.0,lightly active,NaN,0,3
6377,6311,30,2.0,very active,NaN,0,3
6386,6320,44,2.0,lightly active,NaN,0,3

In [16]:
df.sleep_quality.value_counts(dropna=False)

sleep_quality
5.0    2721
4.0    2261
3.0     997
NaN     351
1.0     103
Name: count, dtype: int64

In [19]:
df.sleep_quality = df.sleep_quality.fillna(2)

In [21]:
df.sleep_quality.value_counts(dropna=False)

sleep_quality
5.0    2721
4.0    2261
3.0     997
2.0     351
1.0     103
Name: count, dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6433 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   int64
dtypes: float64(2), int64(4), object(1)
memory usage: 351.9+ KB

## 3. Inconsistent Text & Typos Check

* Find any inconsistent text and typos
* Deal with the inconsistent text and typos

In [ ]:
class_mapping = {
    'light':'lightly active',
    'light_activity':'lightly active',
    'lightly active':'lightly active',
    'active':'active',
    'very active':'very active',
}
df.activity_level = df.activity_level.map(class_mapping)
df.activity_level.value_counts()

In [ ]:
df.info()

## 4. Duplicate Data Check

* Find any duplicate data
* Deal with the duplicate data

## 5. Outliers Check

* Find any outliers
* Deal with the outliers

## 6. Data Issues Check

* Quickly explore the updated DataFrame. How do things look now after handling the data issues compared to the original DataFrame?

## 7. Create Columns From Numeric Data

* Read data into Python
* Check the data type of each column
* Create a numeric column using arithmetic
* Create a numeric column using conditional logic

In [9]:
# Create a “Total Spend” column that includes both the pen cost and shipping cost for each sale
# Create a “Free Shipping” column that says yes if the sale included free shipping, and no otherwise

## 8. Create Columns From DateTime Data

* Calculate the difference between two datetime columns and save it as a new column
* Take the average of a column

In [10]:
# Calculate the number of days between the purchase and delivery date for each sale
# Save it as a new column called “Delivery Time”
# What were the average days from purchase to delivery?

## 9. Create Columns From Text Data

* Split one column into multiple columns
* Create a Boolean column (True / False) to show whether a text field contains particular words

In [11]:
# Split the reviews on the “|” character to create two new columns: “User Name” and “Review Text”
# Create a “Leak or Spill” column that flags the reviews that mention either “leak” or “spill”