# Assignments: Prepping for Modeling

## 1. Create a Single Table

Hi there,

We just finished collecting our Q2 book sales data. Can you help us create one giant table that includes:

* April, May and June’s book sales
* Customer data

Each table has a field called customer_id that links all the tables together.

I’ve attached four files.

Thanks!\
Brooke

In [1]:
# Read all four files into a Jupyter Notebook
import pandas as pd

df_april = pd.read_excel('../Data/Book_Sales_April.xlsx')
df_may = pd.read_excel('../Data/Book_Sales_May.xlsx')
df_june = pd.read_excel('../Data/Book_Sales_June.xlsx')
df_customers = pd.read_csv('../Data/Book_Customers.csv')

In [2]:
df_april.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02

In [3]:
df_may.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date
0,414,109,The Concert Hall,Adults,Fiction,22.72,4.7,Online,2023-05-01
1,415,110,Space and Time,Adults,Fiction,21.58,3.7,In Person,2023-05-04
2,416,101,Rainbows,Children,Fiction,10.25,4.7,Online,2023-05-04
3,417,104,The Speed of Light,Adults,Fiction,20.32,4.1,In Person,2023-05-04
4,418,106,Real Dinosaurs,Children,Non-Fiction,9.99,3.4,In Person,2023-05-04

In [4]:
df_june.head()

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date
0,432,117,Blue Waters,Adults,Fiction,23.98,2.6,Online,2023-06-05
1,433,118,The Cave,Adults,Fiction,24.99,4.7,Online,2023-06-07
2,434,106,Best Dinosaur Book Ever,Children,Non-Fiction,10.49,4.7,In Person,2023-06-08
3,435,103,Peter Penn: The Untold Story,Adults,Non-Fiction,27.90,4.8,In Person,2023-06-08
4,436,101,Everything is Amazing,Children,Fiction,4.99,3.9,In Person,2023-06-08

In [5]:
df_customers.head()

   Customer ID Customer Name  Age Has School Aged Children Has_Pets
0          101     Alexander   36                      Yes       No
1          102         Mason   16                       No       No
2          103         Ethan   55                       No       No
3          104        Daniel   70                       No       No
4          105       Michael   18                       No      Yes

In [6]:
# Concatenate the April, May and June book sales DataFrames
df_sales = pd.concat([df_april, df_may, df_june]).reset_index(drop=True)

In [7]:
df_sales

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02
5,406,103,Brooke Reeder's Memoir,Adults,Non-Fiction,27.50,2.1,In Person,2023-04-02
6,407,104,The Last Day,Adults,Fiction,22.00,4.9,Online,2023-04-02
7,408,105,Summer Sun,Adults,Fiction,21.50,3.4,Online,2023-04-02
8,409,101,Glitter Everything,Children,Fiction,7.49,2.7,Online,2023-04-15
9,410,102,All About the Ocean,Teens,Non-Fiction,19.99,4.2,Online,2023-04-25
10,411,106,Dinosaurs Are Cool,Children,Fiction,8.99,2.5,Online,2023-04-25
11,412,107,Intro to Jupyter Notebooks,Adults,Non-Fiction,25.99,4.9,Online,2023-04-25
12,413,108,The Moon Smiles,Children,Fiction,9.20,3.2,In Person,2023-04-26
13,414,109,The Concert Hall,Adults,Fiction,22.72,4.7,Online,2023-05-01
14,415,110,Space and Time,Adults,Fiction,21.58,3.7,In Person,2023-05-04
15,416,101,Rainbows,Children,Fiction,10.25,4.7,Online,2023-05-04
16,417,104,The Speed of Light,Adults,Fiction,20.32,4.1,In Person,2023-05-04
17,418,106,Real Dinosaurs,Children,Non-Fiction,9.99,3.4,In Person,2023-05-04
18,419,106,Dino Dig,Children,Non-Fiction,10.99,4.7,In Person,2023-05-04
19,420,111,Star Battles: Part 1,Teens,Fiction,13.50,2.3,In Person,2023-05-04
20,421,111,Star Battles: Part 2,Teens,Fiction,13.50,2.8,In Person,2023-05-04
21,422,112,The Forgotten Planet,Teens,Non-Fiction,17.75,4.6,In Person,2023-05-04
22,423,113,Cooking Recipes,Adults,Non-Fiction,28.99,3.8,Online,2023-05-12
23,424,114,Jumping for Joy,Adults,Non-Fiction,28.50,4.2,Online,2023-05-12
24,425,115,Light On Light Off,Adults,Non-Fiction,27.60,4.2,Online,2023-05-12
25,426,103,Sarah Song's Memoir,Adults,Non-Fiction,27.70,4.0,In Person,2023-05-21
26,427,106,Which Dino is Best?,Children,Non-Fiction,8.99,2.6,In Person,2023-05-22
27,428,101,Unicorns Are The Best,Children,Fiction,4.99,2.3,Online,2023-05-23
28,429,111,Star Battles: Part 3,Teens,Fiction,13.50,4.4,Online,2023-05-24
29,430,112,Our Wonderous Planet,Teens,Non-Fiction,17.75,4.5,In Person,2023-05-25
30,431,116,Who's There,Adults,Fiction,24.99,2.1,Online,2023-05-26
31,432,117,Blue Waters,Adults,Fiction,23.98,2.6,Online,2023-06-05
32,433,118,The Cave,Adults,Fiction,24.99,4.7,Online,2023-06-07
33,434,106,Best Dinosaur Book Ever,Children,Non-Fiction,10.49,4.7,In Person,2023-06-08
34,435,103,Peter Penn: The Untold Story,Adults,Non-Fiction,27.90,4.8,In Person,2023-06-08
35,436,101,Everything is Amazing,Children,Fiction,4.99,3.9,In Person,2023-06-08
36,437,101,Everything is Covered in Glitter,Children,Fiction,5.99,4.3,In Person,2023-06-08
37,438,111,Star Battles: Part 4,Teens,Fiction,13.50,4.5,In Person,2023-06-11
38,439,111,Star Battles: Part 5,Teens,Fiction,13.50,3.0,In Person,2023-06-11
39,440,108,The Sun Shines,Children,Fiction,6.79,3.8,In Person,2023-06-11
40,441,119,Coding in Python,Adults,Non-Fiction,29.50,4.9,Online,2023-06-20
41,442,120,Silly Jokes for Kids,Children,Fiction,14.99,3.5,In Person,2023-06-20
42,443,120,Silly Stories for Kids,Children,Fiction,14.99,3.5,In Person,2023-06-20
43,444,121,One Quiet Night,Adults,Fiction,21.50,2.9,Online,2023-06-20
44,445,122,Midnight Saga: Part 1,Teens,Fiction,14.49,3.6,In Person,2023-06-20
45,446,122,Midnight Saga: Part 2,Teens,Fiction,14.49,2.7,In Person,2023-06-22
46,447,122,Midnight Saga: Part 3,Teens,Fiction,14.49,2.1,In Person,2023-06-22
47,448,123,50 Recipes for Weeknights,Adults,Non-Fiction,29.99,3.8,Online,2023-06-23
48,449,124,Music for the Soul,Adults,Fiction,21.30,4.1,Online,2023-06-25
49,450,125,Books Books Books,Adults,Fiction,22.22,4.8,In Person,2023-06-27

In [22]:
# Join the newly created book sales DataFrame with the customers DataFrame on customer_id
# Which type of join do you think would work best here?
df = df_sales.merge(df_customers, how="left", on="Customer ID")
df

,Purchase ID,Customer ID,Book,Audience,Genre,Price,Book Rating,Purchase Location,Purchase Date,Customer Name,Age,Has School Aged Children,Has_Pets
0,401,101,Unicorns Are Cool,Children,Fiction,4.99,3.6,Online,2023-04-01,Alexander,36,Yes,No
1,402,101,I Love Unicorns,Children,Fiction,5.99,4.1,Online,2023-04-01,Alexander,36,Yes,No
2,403,102,All About Turtles,Teens,Non-Fiction,19.99,3.3,In Person,2023-04-02,Mason,16,No,No
3,404,102,All About Whales,Teens,Non-Fiction,19.99,2.5,In Person,2023-04-02,Mason,16,No,No
4,405,102,All About Dolphins,Teens,Non-Fiction,19.99,4.2,In Person,2023-04-02,Mason,16,No,No
5,406,103,Brooke Reeder's Memoir,Adults,Non-Fiction,27.50,2.1,In Person,2023-04-02,Ethan,55,No,No
6,407,104,The Last Day,Adults,Fiction,22.00,4.9,Online,2023-04-02,Daniel,70,No,No
7,408,105,Summer Sun,Adults,Fiction,21.50,3.4,Online,2023-04-02,Michael,18,No,Yes
8,409,101,Glitter Everything,Children,Fiction,7.49,2.7,Online,2023-04-15,Alexander,36,Yes,No
9,410,102,All About the Ocean,Teens,Non-Fiction,19.99,4.2,Online,2023-04-25,Mason,16,No,No
10,411,106,Dinosaurs Are Cool,Children,Fiction,8.99,2.5,Online,2023-04-25,Matthew,40,Yes,No
11,412,107,Intro to Jupyter Notebooks,Adults,Non-Fiction,25.99,4.9,Online,2023-04-25,Samuel,49,Yes,No
12,413,108,The Moon Smiles,Children,Fiction,9.20,3.2,In Person,2023-04-26,Joseph,42,Yes,No
13,414,109,The Concert Hall,Adults,Fiction,22.72,4.7,Online,2023-05-01,Jackson,64,No,No
14,415,110,Space and Time,Adults,Fiction,21.58,3.7,In Person,2023-05-04,David,67,No,Yes
15,416,101,Rainbows,Children,Fiction,10.25,4.7,Online,2023-05-04,Alexander,36,Yes,No
16,417,104,The Speed of Light,Adults,Fiction,20.32,4.1,In Person,2023-05-04,Daniel,70,No,No
17,418,106,Real Dinosaurs,Children,Non-Fiction,9.99,3.4,In Person,2023-05-04,Matthew,40,Yes,No
18,419,106,Dino Dig,Children,Non-Fiction,10.99,4.7,In Person,2023-05-04,Matthew,40,Yes,No
19,420,111,Star Battles: Part 1,Teens,Fiction,13.50,2.3,In Person,2023-05-04,Carter,17,No,No
20,421,111,Star Battles: Part 2,Teens,Fiction,13.50,2.8,In Person,2023-05-04,Carter,17,No,No
21,422,112,The Forgotten Planet,Teens,Non-Fiction,17.75,4.6,In Person,2023-05-04,Owen,17,No,No
22,423,113,Cooking Recipes,Adults,Non-Fiction,28.99,3.8,Online,2023-05-12,Sebastian,53,No,No
23,424,114,Jumping for Joy,Adults,Non-Fiction,28.50,4.2,Online,2023-05-12,Evelyn,20,No,No
24,425,115,Light On Light Off,Adults,Non-Fiction,27.60,4.2,Online,2023-05-12,Abigail,19,No,Yes
25,426,103,Sarah Song's Memoir,Adults,Non-Fiction,27.70,4.0,In Person,2023-05-21,Ethan,55,No,No
26,427,106,Which Dino is Best?,Children,Non-Fiction,8.99,2.6,In Person,2023-05-22,Matthew,40,Yes,No
27,428,101,Unicorns Are The Best,Children,Fiction,4.99,2.3,Online,2023-05-23,Alexander,36,Yes,No
28,429,111,Star Battles: Part 3,Teens,Fiction,13.50,4.4,Online,2023-05-24,Carter,17,No,No
29,430,112,Our Wonderous Planet,Teens,Non-Fiction,17.75,4.5,In Person,2023-05-25,Owen,17,No,No
30,431,116,Who's There,Adults,Fiction,24.99,2.1,Online,2023-05-26,Emily,51,No,No
31,432,117,Blue Waters,Adults,Fiction,23.98,2.6,Online,2023-06-05,Elizabeth,37,No,No
32,433,118,The Cave,Adults,Fiction,24.99,4.7,Online,2023-06-07,Avery,32,No,No
33,434,106,Best Dinosaur Book Ever,Children,Non-Fiction,10.49,4.7,In Person,2023-06-08,Matthew,40,Yes,No
34,435,103,Peter Penn: The Untold Story,Adults,Non-Fiction,27.90,4.8,In Person,2023-06-08,Ethan,55,No,No
35,436,101,Everything is Amazing,Children,Fiction,4.99,3.9,In Person,2023-06-08,Alexander,36,Yes,No
36,437,101,Everything is Covered in Glitter,Children,Fiction,5.99,4.3,In Person,2023-06-08,Alexander,36,Yes,No
37,438,111,Star Battles: Part 4,Teens,Fiction,13.50,4.5,In Person,2023-06-11,Carter,17,No,No
38,439,111,Star Battles: Part 5,Teens,Fiction,13.50,3.0,In Person,2023-06-11,Carter,17,No,No
39,440,108,The Sun Shines,Children,Fiction,6.79,3.8,In Person,2023-06-11,Joseph,42,Yes,No
40,441,119,Coding in Python,Adults,Non-Fiction,29.50,4.9,Online,2023-06-20,Ella,48,No,No
41,442,120,Silly Jokes for Kids,Children,Fiction,14.99,3.5,In Person,2023-06-20,Scarlett,35,Yes,Yes
42,443,120,Silly Stories for Kids,Children,Fiction,14.99,3.5,In Person,2023-06-20,Scarlett,35,Yes,Yes
43,444,121,One Quiet Night,Adults,Fiction,21.50,2.9,Online,2023-06-20,Chloe,25,No,No
44,445,122,Midnight Saga: Part 1,Teens,Fiction,14.49,3.6,In Person,2023-06-20,Victoria,15,No,No
45,446,122,Midnight Saga: Part 2,Teens,Fiction,14.49,2.7,In Person,2023-06-22,Victoria,15,No,No
46,447,122,Midnight Saga: Part 3,Teens,Fiction,14.49,2.1,In Person,2023-06-22,Victoria,15,No,No
47,448,123,50 Recipes for Weeknights,Adults,Non-Fiction,29.99,3.8,Online,2023-06-23,Madison,28,Yes,No
48,449,124,Music for the Soul,Adults,Fiction,21.30,4.1,Online,2023-06-25,Grace,23,No,No
49,450,125,Books Books Books,Adults,Fiction,22.22,4.8,In Person,2023-06-27,Hannah,24,No,Yes

## 2. Prepare Rows for Modeling

Hi again,

We are trying to predict which customers will purchase a book this month.

Can you reformat the data you compiled earlier this week so that it’s ready to be input into a model, with each row representing a customer instead of a purchase?

Thanks!\
Brooke

In [32]:
# What should one row of data look like for the model?
df_prev = df[df['Purchase Date'].dt.month < 6]
df_now = df[df['Purchase Date'].dt.month == 6]

In [ ]:
# Create a column called 'June Purchases' that sums up all purchases in June
df_purchase = df_now.groupby('Customer Name').size().reset_index(name='June Purchases')
df_purchase

   Customer Name  June Purchases
0      Alexander               2
1          Avery               1
2         Carter               2
3          Chloe               1
4      Elizabeth               1
5           Ella               1
6          Ethan               1
7          Grace               1
8         Hannah               1
9         Joseph               1
10       Madison               1
11       Matthew               1
12      Scarlett               2
13      Victoria               3

In [54]:
# Create a column called 'Total Spend' that sums up the prices of all the books that were purchased in April and May
df_total_spend = df_prev.groupby('Customer Name').Price.sum().reset_index(name='Total Spend')
df_total_spend

   Customer Name  Total Spend
0        Abigail        27.60
1      Alexander        33.71
2         Carter        40.50
3         Daniel        42.32
4          David        21.58
5          Emily        24.99
6          Ethan        55.20
7         Evelyn        28.50
8        Jackson        22.72
9         Joseph         9.20
10         Mason        79.96
11       Matthew        38.96
12       Michael        21.50
13          Owen        35.50
14        Samuel        25.99
15     Sebastian        28.99

In [56]:
# Combine the 'June Purchases' and 'Total Spend' columns into a single DataFrame for modeling
df = df_purchase.merge(df_total_spend, how='left', on='Customer Name').fillna(0)
df

   Customer Name  June Purchases  Total Spend
0      Alexander               2        33.71
1          Avery               1         0.00
2         Carter               2        40.50
3          Chloe               1         0.00
4      Elizabeth               1         0.00
5           Ella               1         0.00
6          Ethan               1        55.20
7          Grace               1         0.00
8         Hannah               1         0.00
9         Joseph               1         9.20
10       Madison               1         0.00
11       Matthew               1        38.96
12      Scarlett               2         0.00
13      Victoria               3         0.00

## 3. Prepare Columns for Modeling

Hi again,

Thanks for your help earlier this week! We just learned that we also have to make all of the data numeric before inputting it into a predictive model.

Can you turn the Audience text field into a numeric field?

Thanks!\
Brooke

In [13]:
# Change the Audience field into a dummy variable

In [14]:
# Using the Audience dummy variables, create three new columns that contain
# the number of Adult / Children / Teen books purchased by each customer

In [15]:
# Combine the three new columns back with the customer-level data

## 4. Feature Engineering

Hi again,

I have one final request for you.

As a reminder, our goal is to try and predict which customer will purchase a book this month.

Can you create new features that you think will do a good job making a prediction?

Thanks!\
Brooke

In [16]:
# what features could do a good job predicting june purchases?

In [17]:
# create the feature

In [18]:
# add it to the dataframe for modeling

In [19]:
# create another feature

In [20]:
# add it to the dataframe for modeling

In [21]:
# view the final dataframe that is ready to be input into a model