In [1]:
import numpy as np
import pandas as pd

In [2]:
run_times = pd.read_excel('./Data/Run Times.xlsx')

In [3]:
run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [4]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                     object
dtype: object

In [5]:
run_times.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      object
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      object
 4   Run Date      5 non-null      datetime64[ns]
 5   Race Date     5 non-null      datetime64[ns]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      object
dtypes: bool(1), datetime64[ns](2), float64(1), object(4)
memory usage: 417.0+ bytes

In [6]:
# 문자열이면 계산이나 평균이 안나오기 때문에 숫자나 날짜로 변환한다
# 방해되는 $ 나 , 같은 문자는 replace 로 제거한다
run_times.Fee = pd.to_numeric(run_times.Fee.str.replace('$', '').str.replace(',', ''))

In [7]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [8]:
run_times['Warm Up Time']

0      3.5
1      3.5
2    3 min
3      2.2
4        2
Name: Warm Up Time, dtype: object

In [9]:
run_times['Warm Up Time'] = pd.to_numeric(run_times['Warm Up Time'].astype('str').str.replace(' min', ''))

In [10]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time           float64
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [11]:
run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3.0,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2.0,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

In [12]:
# 머신러닝 모델이 불리언값을 사용할 수 있도록 정수로 바꿔준다
run_times.Rain.astype('int')

0    0
1    1
2    0
3    0
4    0
Name: Rain, dtype: int64

In [13]:
alarm = pd.read_excel('./Data/Alarm Survey Data.xlsx')

In [14]:
alarm.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3.0,active,3.0,1,5 stars
1,2,31,3.0,light,3.0,3,3 stars
2,3,18,0.0,light_activity,4.0,1,1 stars
3,4,42,4.0,active,4.0,1,4 stars
4,5,30,1.0,light_activity,1.0,4,3 stars

In [15]:
alarm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 351.9+ KB

In [16]:
alarm.alarm_rating = pd.to_numeric(alarm['alarm_rating'].astype('str').str.replace(' stars', ''))

In [17]:
alarm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   int64
dtypes: float64(2), int64(4), object(1)
memory usage: 351.9+ KB

In [18]:
# Missing Data 결측치 처리
df = pd.read_excel('./Data/Student Grades.xlsx')

In [19]:
np.nan

nan

In [20]:
pd.NA

In [21]:
None

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  84 non-null     object
 1   Class    83 non-null     object
 2   Year     80 non-null     object
 3   Grade    82 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.8+ KB

In [23]:
df.isna().sum()

Student    2
Class      3
Year       6
Grade      4
dtype: int64

In [24]:
df.head(10)

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
5     Mason  Freshman Seminar  Freshman   90.0
6  Isabella  Freshman Seminar  Freshman   90.0
7     Jacob  Freshman Seminar       NaN   88.0
8   William  Freshman Seminar       NaN   89.0
9     Ethan  Freshman Seminar       NaN   86.0

In [ ]:
# 결측치만 조회
df[df.isna().any(axis=1)]

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
83      NaN                        EDA  Junior   84.0
84    Gavin                        EDA  Senior    NaN
85   Calvin                        NaN     NaN  100.0