In [1]:
import numpy as np
import pandas as pd

In [2]:
run_times = pd.read_excel('./Data/Run Times.xlsx')

In [3]:
run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [4]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                     object
dtype: object

In [5]:
run_times.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      object
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      object
 4   Run Date      5 non-null      datetime64[ns]
 5   Race Date     5 non-null      datetime64[ns]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      object
dtypes: bool(1), datetime64[ns](2), float64(1), object(4)
memory usage: 417.0+ bytes

In [6]:
# 문자열이면 계산이나 평균이 안나오기 때문에 숫자나 날짜로 변환한다
# 방해되는 $ 나 , 같은 문자는 replace 로 제거한다
run_times.Fee = pd.to_numeric(run_times.Fee.str.replace('$', '').str.replace(',', ''))

In [7]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [8]:
run_times['Warm Up Time']

0      3.5
1      3.5
2    3 min
3      2.2
4        2
Name: Warm Up Time, dtype: object

In [9]:
run_times['Warm Up Time'] = pd.to_numeric(run_times['Warm Up Time'].astype('str').str.replace(' min', ''))

In [10]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time           float64
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [11]:
run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3.0,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2.0,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

In [12]:
# 머신러닝 모델이 불리언값을 사용할 수 있도록 정수로 바꿔준다
run_times.Rain.astype('int')

0    0
1    1
2    0
3    0
4    0
Name: Rain, dtype: int64

In [13]:
alarm = pd.read_excel('./Data/Alarm Survey Data.xlsx')

In [14]:
alarm.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3.0,active,3.0,1,5 stars
1,2,31,3.0,light,3.0,3,3 stars
2,3,18,0.0,light_activity,4.0,1,1 stars
3,4,42,4.0,active,4.0,1,4 stars
4,5,30,1.0,light_activity,1.0,4,3 stars

In [15]:
alarm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 351.9+ KB

In [16]:
alarm.alarm_rating = pd.to_numeric(alarm['alarm_rating'].astype('str').str.replace(' stars', ''))

In [17]:
alarm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   int64
dtypes: float64(2), int64(4), object(1)
memory usage: 351.9+ KB

In [18]:
# Missing Data 결측치 처리
df = pd.read_excel('./Data/Student Grades.xlsx')

In [19]:
np.nan

nan

In [20]:
pd.NA

In [21]:
None

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  84 non-null     object
 1   Class    83 non-null     object
 2   Year     80 non-null     object
 3   Grade    82 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.8+ KB

In [23]:
df.isna().sum()

Student    2
Class      3
Year       6
Grade      4
dtype: int64

In [24]:
df.head(10)

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
5     Mason  Freshman Seminar  Freshman   90.0
6  Isabella  Freshman Seminar  Freshman   90.0
7     Jacob  Freshman Seminar       NaN   88.0
8   William  Freshman Seminar       NaN   89.0
9     Ethan  Freshman Seminar       NaN   86.0

In [ ]:
# 결측치만 조회
df[df.isna().any(axis=1)]

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
83      NaN                        EDA  Junior   84.0
84    Gavin                        EDA  Senior    NaN
85   Calvin                        NaN     NaN  100.0

In [ ]:
# dropna() : nan 있으면 행 제거

# 학생과 클래스가 없을떄만 제거할땐
df[df.isna().any(axis=1)].dropna(subset=['Student', 'Class'])

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
84    Gavin                        EDA  Senior    NaN

In [28]:
df[df.Grade.isna()]

    Student                      Class    Year  Grade
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
84    Gavin                        EDA  Senior    NaN

In [29]:
df.Grade.mean()

np.float64(85.70731707317073)

In [ ]:
# inplace : 원본에 반영
df.Grade.fillna(df.Grade.mean(), inplace=True)

In [33]:
df.Grade

0      86.000000
1      86.000000
2      86.000000
3      87.000000
4      90.000000
         ...
81     85.707317
82     85.707317
83     84.000000
84     85.707317
85    100.000000
Name: Grade, Length: 86, dtype: float64

In [34]:
df[df.isna().any(axis=1)]

    Student             Class    Year       Grade
7     Jacob  Freshman Seminar     NaN   88.000000
8   William  Freshman Seminar     NaN   89.000000
9     Ethan  Freshman Seminar     NaN   86.000000
81      NaN               NaN     NaN   85.707317
82  Bennett               NaN     NaN   85.707317
83      NaN               EDA  Junior   84.000000
85   Calvin               NaN     NaN  100.000000

In [37]:
df[df.Class=='Freshman Seminar']

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar       NaN   88.0
8    William  Freshman Seminar       NaN   89.0
9      Ethan  Freshman Seminar       NaN   86.0
10       Ava  Freshman Seminar  Freshman   88.0
11   Michael  Freshman Seminar  Freshman   88.0

In [38]:
# Freshman Seminar 클래스는 신입생일 것이기 때문에 Freshman 으로 채우자
df.Year = np.where(df.Year.isna(), 'Freshman', df.Year)
df

    Student             Class      Year       Grade
0      Emma  Freshman Seminar  Freshman   86.000000
1    Olivia  Freshman Seminar  Freshman   86.000000
2      Noah  Freshman Seminar  Freshman   86.000000
3    Sophia  Freshman Seminar  Freshman   87.000000
4      Liam  Freshman Seminar  Freshman   90.000000
..      ...               ...       ...         ...
81      NaN               NaN  Freshman   85.707317
82  Bennett               NaN  Freshman   85.707317
83      NaN               EDA    Junior   84.000000
84    Gavin               EDA    Senior   85.707317
85   Calvin               NaN  Freshman  100.000000

[86 rows x 4 columns]

In [39]:
df[df.Class=='Freshman Seminar']

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar  Freshman   88.0
8    William  Freshman Seminar  Freshman   89.0
9      Ethan  Freshman Seminar  Freshman   86.0
10       Ava  Freshman Seminar  Freshman   88.0
11   Michael  Freshman Seminar  Freshman   88.0

In [40]:
df_alarm = pd.read_excel('./Data/Alarm Survey Data.xlsx')

In [41]:
df_alarm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 351.9+ KB

In [43]:
df_alarm.isna().sum()

survey_id               0
age                     0
number_of_children      0
activity_level          0
sleep_quality         351
number_of_snoozes       0
alarm_rating            0
dtype: int64

In [51]:
df_alarm[df_alarm.isna().any(axis=1)]

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
10,11,28,2.0,light_activity,NaN,3,4 stars
18,19,38,2.0,lightly active,NaN,1,5 stars
23,24,24,2.0,very active,NaN,1,5 stars
26,27,25,2.0,lightly active,NaN,1,2 stars
28,29,29,2.0,lightly active,NaN,1,2 stars
...,...,...,...,...,...,...,...
6310,6311,30,2.0,very active,NaN,0,3 stars
6319,6320,44,2.0,lightly active,NaN,0,3 stars
6375,6309,32,3.0,light,NaN,0,3 stars
6377,6311,30,2.0,very active,NaN,0,3 stars
6386,6320,44,2.0,lightly active,NaN,0,3 stars

In [52]:
df_alarm.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3.0,active,3.0,1,5 stars
1,2,31,3.0,light,3.0,3,3 stars
2,3,18,0.0,light_activity,4.0,1,1 stars
3,4,42,4.0,active,4.0,1,4 stars
4,5,30,1.0,light_activity,1.0,4,3 stars

In [53]:
df_alarm.sleep_quality.fillna(df_alarm.sleep_quality.mean(), inplace=True)
df_alarm.isna().sum()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_12908\572413466.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_alarm.sleep_quality.fillna(df_alarm.sleep_quality.mean(), inplace=True)

survey_id             0
age                   0
number_of_children    0
activity_level        0
sleep_quality         0
number_of_snoozes     0
alarm_rating          0
dtype: int64

In [54]:
df_alarm

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3.0,active,3.0,1,5 stars
1,2,31,3.0,light,3.0,3,3 stars
2,3,18,0.0,light_activity,4.0,1,1 stars
3,4,42,4.0,active,4.0,1,4 stars
4,5,30,1.0,light_activity,1.0,4,3 stars
...,...,...,...,...,...,...,...
6428,6362,27,2.0,active,5.0,0,5 stars
6429,6363,31,1.0,light,4.0,0,4 stars
6430,6364,26,0.0,lightly active,5.0,0,3 stars
6431,6365,27,1.0,active,5.0,0,3 stars
6432,6366,18,0.0,lightly active,4.0,0,1 stars

In [55]:
df_alarm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6433 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 351.9+ KB

In [57]:
df = pd.read_excel('./Data/Student Grades.xlsx')
df.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [58]:
df.Class.value_counts()

Class
Intro to Python              25
Intro to SQL                 20
EDA                          13
Freshman Seminar             12
Exploratory Data Analysis    12
Python                        1
Name: count, dtype: int64

In [59]:
df[df.Class.isin(['Exploratory Data Analysis', 'EDA'])]

      Student                      Class       Year  Grade
58     Evelyn  Exploratory Data Analysis  Sophomore   89.0
59       Jack  Exploratory Data Analysis  Sophomore   84.0
60       Ella  Exploratory Data Analysis  Sophomore  200.0
61      Chloe  Exploratory Data Analysis  Sophomore   87.0
62     Landon  Exploratory Data Analysis     Junior    NaN
63  Christian  Exploratory Data Analysis     Junior   77.0
64     Jordan  Exploratory Data Analysis     Junior   83.0
65   Jonathan  Exploratory Data Analysis     Junior   82.0
66       Levi  Exploratory Data Analysis     Junior   91.0
67   Victoria  Exploratory Data Analysis     Junior   90.0
68     Aubrey  Exploratory Data Analysis     Junior   83.0
69      Jaxon  Exploratory Data Analysis     Junior   64.0
70     Julian                        EDA     Junior   95.0
71      Grace                        EDA     Junior   77.0
72     Isaiah                        EDA     Junior   88.0
73    Cameron                        EDA     Junior   72.0
74        Eli                        EDA     Junior   92.0
75      Angel                        EDA     Junior   79.0
76       Zoey                        EDA     Junior   91.0
77      Aaron                        EDA     Junior   85.0
78    Charles                        EDA     Junior   93.0
79     Connor                        EDA     Junior   91.0
80      Riley                        EDA     Junior   87.0
83        NaN                        EDA     Junior   84.0
84      Gavin                        EDA     Senior    NaN

In [60]:
df[df.Class.isin(['Intro to Python', 'Python'])]

      Student            Class      Year  Grade
12  Alexander  Intro to Python  Freshman   85.0
13      Logan  Intro to Python  Freshman   85.0
14      James  Intro to Python  Freshman   82.0
15     Daniel  Intro to Python  Freshman   85.0
16     Elijah  Intro to Python  Freshman   85.0
17   Benjamin  Intro to Python  Freshman   81.0
18        Mia  Intro to Python  Freshman   80.0
19        Mia           Python  Freshman   80.0
20     Jayden  Intro to Python  Freshman   82.0
21      Aiden  Intro to Python  Freshman   86.0
22    Matthew  Intro to Python  Freshman   87.0
23      Emily  Intro to Python  Freshman   78.0
24    Jackson  Intro to Python  Freshman   88.0
25      Lucas  Intro to Python  Freshman   77.0
26      David  Intro to Python  Freshman   74.0
27     Joseph  Intro to Python  Freshman   93.0
28    Abigail  Intro to Python  Freshman   89.0
29      Avery  Intro to Python  Freshman   79.0
30    Anthony  Intro to Python  Freshman   84.0
31      Dylan  Intro to Python  Freshman   84.0
32     Andrew  Intro to Python  Freshman   94.0
33     Carter  Intro to Python  Freshman   95.0
34     Samuel  Intro to Python  Freshman   83.0
35    Gabriel  Intro to Python  Freshman   82.0
36     Joshua  Intro to Python  Freshman   71.0
37       John  Intro to Python  Freshman   50.0